### PR TITLE
BEvm TS fixes

### PR DESCRIPTION
**Pull request by cgrigis**
**What this PR does**

This PR fixes some issues with the TypeScript of BEvm, as noticed when trying to use the package from an external client.

---

🙅‍ Friendly checklist:

- [x] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [x] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [x] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [x] 3. Code comments are added on tests to explain what they do.
- [x] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [x] 5. Hard limit of 80 chars is always respected.
- [x] 6. Changes are backward compatible.
- [x] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [x] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [x] 9. There are no magic values.

### CODE REVIEW

**Comment by ineiti** [comment]
Is there a possibility to add a test for any of this? It seems to be more than just the dependencies (which are difficult to test)...

**Comment by cgrigis** [comment]
The changes are:
1. A superfluous dependency (eliminating it removes a warning)
1. Some missing dependencies (which I guess worked in the tests because they exist by indirection)
1. Changes to the `BEvmInstance.call()` signature, which is used in the tests in `bevm-instance.spec.ts`

What additional tests did you have in mind?  I am not sure how to test for 2. from within the package...

**Comment by ineiti** [comment]
For the `package.json` it was more out of curiosity.
For https://github.com/dedis/cothority/pull/2343/files#diff-d0e8c15a0a0bc30e1d6e0e6375f5269fR352 it looks like this method should be tested, because you changed its signature but I don't see a changed test...

**Comment by cgrigis** [comment]
> For the `package.json` it was more out of curiosity.

I agree with the question though :)  I am wondering now, does what I said make sense? Without explicitly adding `elliptic` and `rlp` to `package.json` the tests were passing fine. But when I try to use the package from StackBlitz, it complains about the missing `elliptic` and `rlp` unless I explicitly import them...

> For https://github.com/dedis/cothority/pull/2343/files#diff-d0e8c15a0a0bc30e1d6e0e6375f5269fR352 it looks like this method should be tested, because you changed its signature but I don't see a changed test...

I must be missing something :)
https://github.com/dedis/cothority/pull/2343/files#diff-9f9b6e5d8821b65daf68a69434a0af8dL118
https://github.com/dedis/cothority/pull/2343/files#diff-9f9b6e5d8821b65daf68a69434a0af8dL159
?

**Comment by ineiti** [comment]
> I must be missing something :)
> https://github.com/dedis/cothority/pull/2343/files#diff-9f9b6e5d8821b65daf68a69434a0af8dL118
> https://github.com/dedis/cothority/pull/2343/files#diff-9f9b6e5d8821b65daf68a69434a0af8dL159
> ?

I invoke the `sleepy Friday syndrome`...

**Comment by ineiti** [comment]
If you want it merged, put it in R4M...

**Comment by cgrigis** [comment]
> If you want it merged, put it in R4M...

Done. Was just finishing a couple of tests with StackBlitz to see if anything else was missing... looks to be OK now.

**Pull request merged**
