### PR TITLE
Cross-platform syscall for RTime (#422) merged with development branch

### PR DESCRIPTION
**Pull request by mahdiz**
PR #422 commits merged with `cothority/development` branch.

### CODE REVIEW

**Comment by nikkolasg** [comment]
For me, we still need to make sure it works correctly by launching a simulation or two, then I'm ok :)
 @mahdiz Thanks a lot !

**Comment by ineiti** [comment]
I tested it on Mac and it works - great. 

@mahdiz, can I ask you to add a `simul/test_simul.bat` following `simul/test_simul.sh` and run it? I'd like to have a look at the `simul/test_data`-files to see whether they make sense ;)

**Comment by ineiti** [comment]
In the meantime we finished our big rewrite - can you merge with the new branch? We also changed our development-model and are doing the changes directly against `master` now, using `gopkg.in` for stable releases.

**Comment by Liamsi** [comment]
replaced with #485

**Pull request closed without merging**
