### PR TITLE
Added linting to travis

### PR DESCRIPTION
**Pull request by Liamsi**

### CODE REVIEW

**Comment by Liamsi** [comment]
OK, this should implement #269 (similar to what was asked for in https://github.com/dedis/cothority/issues/269#issuecomment-197251933).
Currently, the linter fails on two kinds of checks. Here are two examples:
```
protocols/cosi/packets.go:15:6: type name will be used as cosi.CosiAnnouncement by other packages, and that stutters; consider calling this Announcement 
```
and
```
simul/platform/localhost.go:107:1: exported method Localhost.Deploy should have comment or be unexported
```

**Comment by Liamsi** [comment]
I think the two lints are the only reasonable. Do you all agree @nikkolasg @ineiti @Daeinar ?
Anyways, it is easy to add remove or disable the linter.

**Comment by Liamsi** [comment]
I don't know if it's clever to merge it (as travis will fail). Better would be to comment out the linter script before, and to open an issue which we *all* work on after the more urgent tasks are done (everyone fixes the failing checks of the code he created).

**Comment by ineiti** [comment]
There seem to be two errors - or are they related? Lint fails (of course), but the go-test fails, too...

Besides that I propose we comment out the Travis-inclusion but let the script inside, merge and then we work on documenting stuff.

**Comment by nikkolasg** [comment]
Agree with @Liamsi and @ineiti

**Comment by Liamsi** [comment]
> There seem to be two errors - or are they related? Lint fails (of course), but the go-test fails, too...

I saw that, too. I thought the problem is that the lint-script fails and hence the other parts of the `install:` section aren't done correctly. I will experiment with that and comment out the script if I know exactly if the failing tests are related.

**Comment by Liamsi** [comment]
Moving the installation of golint to `before_install:` helps with the tests (otherwise it overwrites the default `install` routine.

**Comment by Liamsi** [comment]
> There seem to be two errors - or are they related? Lint fails (of course), but the go-test fails, too...

Fixed (see [last travis build](https://travis-ci.org/dedis/cothority/builds/116418580)). I commented out the linter in travis now.

**Comment by ineiti** [comment]
OK, cool. Did you open the issue `Everybody get his code documented`?

Merge +1

**Comment by Liamsi** [comment]
> Did you open the issue Everybody get his code documented?

#275
I merged this myself (as it basically doesn't change any relevant parts of the code and the relevant part in travis.yml is commented)

**Pull request merged**
