### PR TITLE
dbg-library outputs to stderr for dbg.Print,Warning,Error,Fatal,Panic

### PR DESCRIPTION
**Pull request by ineiti**
As title says...

### CODE REVIEW

**Comment by nikkolasg** [comment]
Why stderr for `dbg.Print` ?

**Comment by ineiti** [comment]
Because `dbg.Print` should only be used short-term to get some debugging messages and then disappear. But if you think it should go into stdout, that's also possible.

**Comment by nikkolasg** [comment]
Yes but that does not mean it should be on stderr, at least the name does not imply anything like that. +1 for stdout. Otherwise, OK for merging !

**Comment by nikkolasg** [comment]
BTW, Bryan did not mention it but do you think it makes sense to also include the possibility of writing to a file ?  Like most daemon simply write their logs to a file (or syslog, whatever). Not sure yet.

**Comment by ineiti** [comment]
He did mention something like that. So if you want to add a flag, that's good for me.

**Comment by nikkolasg** [comment]
Do you think it makes sense to it on this PR or another one ?

**Comment by ineiti** [comment]
I think the writing to a file is the job of the cosi-binary, not of the debugging-library. If you want me to add a 'logging'-possibility by redirecting stdout and stderr to log-files, that's possible. But I didn't understand your request to be that.

**Comment by nikkolasg** [comment]
Closed . Refers to https://github.com/dedis/cothority/pull/380

**Pull request closed without merging**
