### PR TITLE
Updated mahdiz rtime

### PR DESCRIPTION
**Pull request by Liamsi**
Merged master into @mahdiz's PR #442

### CODE REVIEW

**Comment by nikkolasg** [comment]
if Travis passes, I'm OK

**Comment by ineiti** [comment]
so we won't have a `.bat`-file?

**Comment by Liamsi** [comment]
I wouldn't have a possibility to run that (no windows), if @mahdiz wants to provide one, I would be happy. Otherwise make it a separate issue.

**Comment by mahdiz** [comment]
Sorry for the delay! I've migrated to unix on my machine (found it much easier :)), but I'll find a windows machine and test it in a few days. Should I upload the simulation log-file?

**Comment by ineiti** [comment]
Hi Mahdiz - cool, welcome on board of the Unix-machines ;)

It would be nice if you could contribute a .bat-file like `simul/test_simul.sh` to the pull-request and the output of a `test_data`. Just to make sure that the data gets created correctly.

**Comment by Liamsi** [comment]
> Sorry for the delay! I've migrated to unix on my machine (found it much easier :)), but I'll find a windows machine and test it in a few days. Should I upload the simulation log-file?

congrats for the unix migration :-) As Linus pointed out it would be great to have this batch file. The easiest way would be to sync your fork and and create a PR against this branch (updated_mahfiz_rtime). I'll make sure that this branch is up to date.

**Comment by Liamsi** [comment]
There seems to be another problem in sda not related to this branch; see the build here https://travis-ci.org/dedis/cothority/builds/146332684 

<details>
<summary>relevant part of the build process</summary>
--- FAIL: TestReconnection (0.63s)
	testutil.go:61: 1 instances of:
		net.runtime_pollWait(0x2b9bdac37c30, 0x72, 0x413029)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x63
		net.(*pollDesc).Wait(0xc820017a30, 0x72, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x56
		net.(*pollDesc).WaitRead(0xc820017a30, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x44
		net.(*netFD).Read(0xc8200179d0, 0xc820539a7c, 0x4, 0x4, 0x0, 0x2b9bdac30110, 0xc8200820b0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:250 +0x27b
		net.(*conn).Read(0xc82002e058, 0xc820539a7c, 0x4, 0x4, 0x0, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/net.go:172 +0x121
		net.(*TCPConn).Read(0xc82002e058, 0xc820539a7c, 0x4, 0x4, 0x0, 0x0, 0x0)
			<autogenerated>:68 +0x7d
		io.ReadAtLeast(0x2b9bdabca600, 0xc82002e058, 0xc820539a7c, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/io/io.go:297 +0x119
		io.ReadFull(0x2b9bdabca600, 0xc82002e058, 0xc820539a7c, 0x4, 0x4, 0x4, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/io/io.go:315 +0x77
		encoding/binary.Read(0x2b9bdabca600, 0xc82002e058, 0x2b9bdac35050, 0xe38230, 0x954a40, 0xc820539a78, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/encoding/binary/binary.go:220 +0x189a
		github.com/dedis/cothority/network.(*TCPConn).Receive(0xc820017a40, 0x2b9bdabca2a0, 0xc8200828c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:362 +0x2d2
		github.com/dedis/cothority/network.(*SecureTCPConn).Receive(0xc82000b0e0, 0x2b9bdabca2a0, 0xc8200828c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:495 +0x98
		github.com/dedis/cothority/sda.(*Host).handleConn(0xc8200f0000, 0x2b9bdabca650, 0xc82000b0e0)
			/home/travis/gopath/src/github.com/dedis/cothority/sda/host.go:428 +0x130
		github.com/dedis/cothority/sda.(*Host).listen.func1(0x2b9bdabca650, 0xc82000b0e0)
			/home/travis/gopath/src/github.com/dedis/cothority/sda/host.go:108 +0x2a0
		created by github.com/dedis/cothority/network.(*SecureTCPHost).Listen.func1
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:239 +0x95e
	testutil.go:61: 1 instances of:
		net.runtime_pollWait(0x2b9bdac37cf0, 0x72, 0x413029)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x63
		net.(*pollDesc).Wait(0xc820017560, 0x72, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x56
		net.(*pollDesc).WaitRead(0xc820017560, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x44
		net.(*netFD).accept(0xc820017500, 0x0, 0x2b9bdac38230, 0xc82000b560)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:426 +0x2f6
		net.(*TCPListener).AcceptTCP(0xc82002e048, 0x97b400, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/tcpsock_posix.go:254 +0x77
		net.(*TCPListener).Accept(0xc82002e048, 0x0, 0x0, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/tcpsock_posix.go:264 +0x4b
		github.com/dedis/cothority/network.(*TCPHost).listen(0xc8200180a0, 0xc820538030, 0xe, 0xc820545e20, 0x0, 0x0)
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:180 +0x1f7
		github.com/dedis/cothority/network.(*SecureTCPHost).Listen(0xc8200202a0, 0xc820539270, 0x0, 0x0)
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:252 +0x73b
		github.com/dedis/cothority/sda.(*Host).listen.func2(0xc8200f0000, 0xc820539270)
			/home/travis/gopath/src/github.com/dedis/cothority/sda/host.go:112 +0x222
		created by github.com/dedis/cothority/sda.(*Host).listen
			/home/travis/gopath/src/github.com/dedis/cothority/sda/host.go:116 +0x382
	testutil.go:61: 1 instances of:
		net.runtime_pollWait(0x2b9bdac37db0, 0x72, 0x413029)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x63
		net.(*pollDesc).Wait(0xc8200175d0, 0x72, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x56
		net.(*pollDesc).WaitRead(0xc8200175d0, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x44
		net.(*netFD).Read(0xc820017570, 0xc820539df4, 0x4, 0x4, 0x0, 0x2b9bdac30110, 0xc8200820b0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:250 +0x27b
		net.(*conn).Read(0xc82002e050, 0xc820539df4, 0x4, 0x4, 0xc820539a7c, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/net.go:172 +0x121
		net.(*TCPConn).Read(0xc82002e050, 0xc820539df4, 0x4, 0x4, 0x0, 0x0, 0x0)
			<autogenerated>:68 +0x7d
		io.ReadAtLeast(0x2b9bdabca600, 0xc82002e050, 0xc820539df4, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/io/io.go:297 +0x119
		io.ReadFull(0x2b9bdabca600, 0xc82002e050, 0xc820539df4, 0x4, 0x4, 0x4, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/io/io.go:315 +0x77
		encoding/binary.Read(0x2b9bdabca600, 0xc82002e050, 0x2b9bdac35050, 0xe38230, 0x954a40, 0xc820539df0, 0x0, 0x0)
			/home/travis/.gimme/versions/go1.6.linux.amd64/src/encoding/binary/binary.go:220 +0x189a
		github.com/dedis/cothority/network.(*TCPConn).Receive(0xc8200175e0, 0x2b9bdabca2a0, 0xc8200828c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:362 +0x2d2
		github.com/dedis/cothority/network.(*SecureTCPConn).Receive(0xc82000ae00, 0x2b9bdabca2a0, 0xc8200828c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
			/home/travis/gopath/src/github.com/dedis/cothority/network/net.go:495 +0x98
		github.com/dedis/cothority/sda.(*Host).handleConn(0xc8200f0000, 0x2b9bdabca650, 0xc82000ae00)
			/home/travis/gopath/src/github.com/dedis/cothority/sda/host.go:428 +0x130
		created by github.com/dedis/cothority/sda.(*Host).Connect
			/home/travis/gopath/src/github.com/dedis/cothority/sda/host.go:154 +0x459
	testutil.go:68: Test leaks 3 gorountines.
Couldn't listen on localhost:2000 : No address worked for listening on this host Error opening listener: listen tcp 0.0.0.0:2000: bind: address already in use.
FAIL	github.com/dedis/cothority/sda	8.361s
</details>

**Comment by mahdiz** [comment]
I can't run a simulation in Windows, because the files in `simul/platform/localhost` seem to be Unix binaries (the exec command in `simul/platform/localhost.go` fails in Windows when running any of the tests in `simul/runfiles`). How can I generate the test binaries?

**Comment by nikkolasg** [comment]
@mahdiz The binaries should be compiled when you run the tests, there's not "test binaries" pre-compiled. What command are you using to run the simulation ? What is exactly the error output ?

One thing you can try is changing in `localhost.go`:168, instead of having `d.runDir + "/" + d.Simulation`, try the os-independant version : `path.Join(d.runDir,d.Simulation)`. In fact, the whole `localhost.go` needs to be changed to use the `path.Join` version. If in any case you don't want to go to that much trouble,  we can open an issue for that, I can try to find time for it this week. 
(Still interested in the output !)
Thanks again for the contribution ;)

**Comment by mahdiz** [comment]
@nikkolasg I'm running the command from `simul/test_simul.sh`:

```bash
simul -debug 1 runfiles\test_randhound.toml
```
Should I run a different command that compiles the tests?

Btw, I've already made the paths os-independant to let the simulation run. I can include them in the current PR if it's okay :) Thanks!

**Comment by nikkolasg** [comment]
The command should be fine. 
> Btw, I've already made the paths os-independant to let the simulation run. I can include them in the current PR if it's okay :) 

Definitely ! Thanks a lot.
And can you still post the output please ?

**Comment by mahdiz** [comment]
Turns out that `cmd.Run()` can only execute files with a `.exe` extension in Windows. The `Build` method in `localhost.go` has to add `.exe` to the simulation binary file name if we're in Windows. I fixed it and added the a `.bat` file for windows. Everything seems to be running smoothly. Here's my `test_data` folder:

[test_data.zip](https://github.com/dedis/cothority/files/384690/test_data.zip)

The new PR is #498.

**Comment by nikkolasg** [comment]
Great ! Ahhh Windows ... :) 
From what I see the results looks consistents but I'll let @Liamsi take another look. 
Regarding the Travis failing what do we do @Liamsi : Do we merge it ? or do we first make a small PR that we merge ourselves to resolve the issue and then see if Travis here is happy again ?
I'm more for the second option, but I'm only working a few hours this morning today so I won't be able to pull it off I guess. What do you think ?

Anyway, @mahdiz thanks a lot for all the work!

**Comment by Liamsi** [comment]
> From what I see the results looks consistents but I'll let @Liamsi take another look. 

Looks good from what I can tell! 

> Regarding the Travis failing what do we do @Liamsi : Do we merge it ? or do we first make a small PR that we merge ourselves to resolve the issue and then see if Travis here is happy again ?

The travis error doesn't interfere with this PR. So I would definitely merge it first. I already open an issue for the travis failing.

The changes in #498 look useful (even independent from the .bat file). We should use platform independent methods (like `path.Join`) where possible.

Thanks a lot @mahdiz

**Comment by nikkolasg** [comment]
OK then I'm good to merge then :)

**Comment by mahdiz** [comment]
Great, thanks :)

**Pull request merged**
