### PR TITLE
cothorityjs: add LeaderSocket

### PR DESCRIPTION
**Pull request by gnarula**
LeaderSocket reads a roster and allows sending messages to the
leader node. As of now the leader node is the first node in the
roster.

### CODE REVIEW

**Comment by gnarula** [comment]
@nikkolasg This is something @ineiti and I discussed earlier this morning. From what I understand, it's only the leader that has the capability to add a new block to the skipchain. This would allow saving some internal requests from conode N to the leader and offer some performance improvements. All the nodes still end up verifying the transaction before it's appended to the chain.

**Comment by ineiti** [comment]
New blocks always have to be proposed by the leader. If another node wants to propose new blocks, this requires a view-change. The new _omniledger_ (insert great music here) implementation will allow nodes to collect transactions that will be collected by the leader and inserted into a new block.

**Comment by nikkolasg** [comment]
I'm not sure centralizing all client requests on one server actually improves performance and reliability. Usually you would expect any nodes can receive transactions and there's some kind of gossiping network that shares every transactions seen. Also, there's lot of problems concerning the fact that only the leader has access to the transactions, he can just choose whatever he wants and no other nodes will be able to detect if he is purposedly dropping some transactions or not, etc...

Anyway, I don't want to interpose, just wanted to raise my concerns about this approach, so it's always in the back of your mind when thinking about the final solution... :)

**Comment by ineiti** [comment]
You're completely right with your comments, this is what we're working on in the new omniledger implementation. But this will unfortunately not be ready for the epfl e-voting schedule.

**Pull request merged**
