### PR TITLE
Examples are better covered in cothority_template repo.

### PR DESCRIPTION
**Pull request by jeffallen**

### CODE REVIEW

**Comment by kc1212** [comment]
Build failing, changing to WIP

**Comment by ineiti** [comment]
Now we have node failing, too ;)

**Comment by ineiti** [comment]
Can you separate this into
- remove examples
- update scmgr (not sure what you're doing there)
- update status

**Comment by jeffallen** [comment]
The status changes were not supposed to be in this PR, they were already checked in by Kelong on Friday. I have rebased this to master, and now only the correct commit is in it.

**Pull request merged**
