### PR TITLE
Adds PaginateBlocks service

### PR DESCRIPTION
**Pull request by nkcr**
This PR implements a new PaginateBlocks service that accepts stream connections.

Is linked with the work of https://github.com/dedis/onet/pull/616, which is part of the "Blockchain visualizer" project.

**Must not be merged**
Split into two different PRs:
- #2192 (Byzcoin service)
- #2193 (js client)

---

New messages:
- PaginateRequest
- PaginateResponse

Update of the cothority/js:
- supports Streaming request
- supports the new PaginateBlocks service

Update the cothority/js websocket connection:
- update the IConnection interface to include a sendStream function

---

🙅‍ Friendly checklist:

- [ ] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [ ] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [ ] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [ ] 3. Code comments are added on tests to explain what they do.
- [ ] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [ ] 5. Hard limit of 80 chars is always respected.
- [ ] 6. Changes are backward compatible.
- [ ] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [ ] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [ ] 9. There are no magic values.

### CODE REVIEW

**Comment by ineiti** [comment]
What is the advantage of this compared to the following:
- fix typescript network connection to keep the connection
- use `GetUpdateChain`
?

**Comment by nkcr** [comment]
|  | `GetUpdateChain` | `PaginateBlocks` |
| - | ------------------- | ----------------- |
| fetch a page of N blocks  | √  | √ |
| request to get K pages asynchronously | client need to do K requests and handle the K promises. | √ |
| re-use the same ws connection | need to fix that | √ |
| fetch pages in reversed-order | x | √ |
| get specific error codes and messages | x | √ |
| can be adapted to the Columbus project | x | √ |

As the last point suggests, I am expecting the `PaginateBlocks` service to be unstable during the course of the project, as we will surely discover new needs. For example I imagine that requesting only the hash of the blocks without their content could be useful to quickly draw a preview of the whole blockchain. 

Of course this doesn't mean we shouldn't fix the typescript network connection

**Comment by ineiti** [comment]
* request to get K pages asynchronously | client need to do K requests and handle the K promises.
  * So you mean that the Paginate can take a cmd like "Give me 5 times 10 blocks", and he will send 5 times 10 blocks?
* fetch pages in reversed-order | x
  * GetUpdateChain can do that, no?
* get specific error codes and messages | x
  * What error codes are missing?
* can be adapted to the Columbus project
  * Do you have some text on the columbus project? I don't know what this is about...

**Comment by nkcr** [comment]
#2192 and #2193 are now merged. Closing.

**Pull request closed without merging**
