### PR TITLE
Bumps @dedis/cothority and @dedis/kyber

### PR DESCRIPTION
**Pull request by nkcr**
**What this PR does**

*See commit message*

---

🙅‍ Friendly checklist:

- [x] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [x] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [x] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [x] 3. Code comments are added on tests to explain what they do.
- [x] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [x] 5. Hard limit of 80 chars is always respected.
- [x] 6. Changes are backward compatible.
- [x] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [x] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [x] 9. There are no magic values.

### CODE REVIEW

**Comment by Gilthoniel** [comment]
This should be merged onto `v3.3.x` branch.

**Comment by ineiti** [comment]
there seems to be some kind of branching-conflict...

**Comment by Gilthoniel** [comment]
So after talking with Jeff, we're moving out of the master/v3 mess thus we can merge this PR in master when it's done. But @nkcr , you still need to update first kyberjs then update cothority to use the new version.

**Comment by jeffallen** [comment]
Will be done in #2139.

**Pull request closed without merging**
