### PR TITLE
pop config path

### PR DESCRIPTION
**Pull request by yurunhub**
create config file path for pop if it does not exist

### CODE REVIEW

**Comment by ineiti** [comment]
Thanks for the PR - some issues:
- it doesn't pass travis: https://travis-ci.org/dedis/cothority/jobs/418761888#L694
   (I think it's a formatting issue - please use `gofmt`)
- the directory should be created in the `write` method
- no need to check if the directory exists - `MkdirAll` will do that for you: https://golang.org/pkg/os/#MkdirAll

**Comment by yurunhub** [comment]
added to write method with gofmt travis is happy

**Comment by ineiti** [comment]
One last thing - it seems it's better to use `filepath` instead of `path`, because `filepath` abstracts the different separators. This article on stackoverflow goes into the details (read 'when do I use each'?). As we _do_ have some people using Windows, this difference is important to us.

https://stackoverflow.com/questions/39181790/whats-the-difference-between-path-path-filepath-packages-in-go

**Comment by ineiti** [comment]
And one very last thing: if you will continue to work on `onet` / `cothority`, please write an email to linus.gasser at epfl dot ch, so that I can invite you into our slack channel.

**Comment by yurunhub** [comment]
changed path->filepath and tested

**Comment by ineiti** [comment]
Cool! Thank you very much.

**Pull request merged**
