### PR TITLE
Send view method call to whole roster

### PR DESCRIPTION
**Pull request by cgrigis**
**What this PR does**

This PR increases the reliability of BEvm view methods called from the frontend by sending the request to all the members of the roster. Currently, it was sent only to the first node in the roster, which seems to be unreliable as connection errors appear regularly when using the Stainless demo.
To ensure view methods are executed with a state that is current, the latest block ID is tracked during transaction calls and sent for view methods: using it, the node determines whether it needs to wait for an updated state before executing the call.

---

🙅‍ Friendly checklist:

- [x] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [x] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [x] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [x] 3. Code comments are added on tests to explain what they do.
- [x] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [x] 5. Hard limit of 80 chars is always respected.
- [x] 6. Changes are backward compatible.
- [x] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [x] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [x] 9. There are no magic values.

### CODE REVIEW

**Comment by cgrigis** [comment]
SonarCloud appears to get confused about what constitutes _new code_. I suspect it might be because my PR comes from the C4DT repo, which has a different master branch. Anyone knows how to handle this?

**Comment by ineiti** [comment]
Yes, good point. IIRC, I had similar problems and just ended up ignoring Sonarcloud... Do you have write access to the dedis/cothority, so that you can do a PR from here?

**Comment by cgrigis** [comment]
I tried a PR from the dedis repo (see #2434) but it seems to have the same outcome, so that is not the reason...

**Comment by cgrigis** [comment]
Closed in favor of #2434.

**Comment by ineiti** [comment]
> It's annoying that we can no longer make clean pull requests from C4DT's fork though...

I agree - if you want to fight SonarCloud over it, feel free. I mostly PR from the repo itself anyway.

**Comment by cgrigis** [comment]
Was there a reason to keep the master branch in the C4DT fork not synchronized with upstream?

**Comment by ineiti** [comment]
None - only lazyness. I wanted to have a cleaner development by using separate repositories. But I don't feel very strongly about this. And if SonarCloud has trouble with that, I'm OK with removing the c4dt/cothority and just keep the dedis/cothority.

**Comment by cgrigis** [comment]
I meant it more in the sense that we can then synchronize master and see if that fixes it on the next PR.

**Comment by ineiti** [comment]
That is included in the `fight with SonarCloud` ;)

**Comment by cgrigis** [comment]
Challenge accepted :)

**Pull request closed without merging**
