### PR TITLE
Byzcoin proof attack

### PR DESCRIPTION
**Pull request by Gilthoniel**
This fixes the Byzcoin proof attack by making sure the roster provided inside the first link is correct and not tampered. It also adds an API to ask for shorter proofs but the default request keeps asking for the proof from the genesis block so that this proof can be shared among peers.

Also: remove duplication of the proof verification already done by the request API

Part of #1959

### CODE REVIEW

**Comment by Gilthoniel** [comment]
Note that I removed the TODO comment about verifying the roster in calypso because the roster is coming from the proof that has been signed by the Cothority.

**Comment by Gilthoniel** [comment]
This doesn't fix the issue as the next step will be to fix the Java and Javascript libraries.

**Comment by ineiti** [comment]
1. I still think that this is a band-aid rather than a fix: the proof in itself is still not secure. If you want to have it secure, you need additional data. So the 'nice' thing about saying that our base-truth is simply the 32-bytes of the byzcoin-ID is gone, as now it also needs the genesis-block itself to prove that it's correct.
2. To optimize it, I would not store the `SkipBlock`, but only the `SkipBlockFix`, as the latter is enough to calculate the byzcoin-ID, so you save some bytes and need to store a little bit less data

**Comment by Gilthoniel** [comment]
>     1. I still think that this is a band-aid rather than a fix: the proof in itself is still not secure. If you want to have it secure, you need additional data. So the 'nice' thing about saying that our base-truth is simply the 32-bytes of the byzcoin-ID is gone, as now it also needs the genesis-block itself to prove that it's correct.

In the case of a short proof (one that doesn't start from the genesis), having the block in the proof is not sufficient because you would need the proof of this block. It assumes that you already know the block beforehand and that you verified it.
Yes, adding the genesis block for full proofs would allow them to be verifiable offline but only for those specific proofs. But this genesis block is needed for most the verification anyway so why would you want to provide it all the time ? An example is the Java client that is fetching the genesis block at the beginning all the time...
> 
>     2. To optimize it, I would not store the `SkipBlock`, but only the `SkipBlockFix`, as the latter is enough to calculate the byzcoin-ID, so you save some bytes and need to store a little bit less data

As I already mentioned, the `SignatureScheme` is used in the hash but because of the protobuf indexing issue, the field has to be in `SkipBlock`.

**Comment by ineiti** [comment]
> As I already mentioned, the SignatureScheme is used in the hash but because of the protobuf indexing issue, the field has to be in SkipBlock.

True - forgot about that :( We're still experimenting in what happens if we have a _real_ protobuf workflow with the `.proto` files that generate also the `.go` files - if you're interested, you can contact Valerian.

**Comment by Gilthoniel** [comment]
That would definitely be an interesting thing to investigate for v4 !

**Pull request merged**
