### PR TITLE
added a time-flag to show the time of the debug-messages

### PR DESCRIPTION
**Pull request by ineiti**
Has a new time-flag to show the time in debug messages

### CODE REVIEW

**Comment by nikkolasg** [comment]
Tried it and have the loong output:
```
2016-03-24 11:31:32.621732282 +0100 CET 3 2016-03-24 11:31:32.621781264 +0100 CET 1 2016-03-24 11:31:32.621820219 +0100 CET 2 2016-03-24 11:31:32.622063191 +0100 CET 3 2016-03-24 11:31:32.622120325 +0100 CET 3 2016-03-24 11:31:32.622478991 +0100 CET 3 2016-03-24 11:31:32.622639717 +0100 CET 3 2016-03-24 11:31:32.622690705 +0100 CET 3 2016-03-24 11:31:32.622792978 +0100 CET 3 2016-03-24 11:31:32.627220417 +0100 CET 3 2016-03-24 11:31:32.627376734 +0100 CET 3 2016-03-24 11:31:32.627788669 +0100 CET 3 2016-03-24 11:31:32.627936716 +0100 CET 3 2016-03-24 11:31:32.633918118 +0100 CET 3 2016-03-24 11:31:32.635476635 +0100 CET 3 2016-03-24 11:31:32.636431561 +0100 CET 3 2016-03-24 11:31:32.639297962 +0100 CET 3 2016-03-24 11:31:32.640734106 +0100 CET 3 2016-03-24 11:31:32.645019134 +0100 CET 3 2016-03-24 11:31:32.645384483 +0100 CET 3 2016-03-24 11:31:32.645419159 +0100 CET 3 2016-03-24 11:31:32.645421337 +0100 CET 3 2016-03-24 11:31:32.645449112 +0100 CET 3 2016-03-24 11:31:32.645457054 +0100 CET 3 2016-03-24 11:31:32.645480736 +0100 CET 3 2016-03-24 11:31:32.645580726 +0100 CET 3 2016-03-24 11:31:32.645598927 +0100 CET 3 2016-03-24 11:31:32.645606899 +0100 CET 3 2016-03-24 11:31:32.645637858 +0100 CET 3 2016-03-24 11:31:32.645645624 +0100 CET 3 2016-03-24 11:31:32.6456456 +0100 CET   3 2016-03-24 11:31:32.645662836 +0100 CET 3 2016-03-24 11:31:32.645667737 +0100 CET 3 2016-03-24 11:31:32.645730009 +0100 CET 3 2016-03-24 11:31:32.645757861 +0100 CET 3 2016-03-24 11:31:32.648014912 +0100 CET 3 2016-03-24 11:31:32.648041423 +0100 CET 3 2016-03-24 11:31:32.648074796 +0100 CET 3 2016-03-24 11:31:32.648098515 +0100 CET 3 2016-03-24 11:31:32.648121839 +0100 CET 3 2016-03-24 11:31:32.648147624 +0100 CET 3 2016-03-24 11:31:32.656113476 +0100 CET
```

When this is solved, I think it could be nice to have a reduced format such as `11:31:32`, or with the date `11:31:32  2016-03-24`. Just something shorter would be OK I think. When you have large screen it's OK, but when you run on your laptop screen, you don't want to go to the end right of the screen to see the actual content. (+ we don't probably need more than the seconds)

Else OK for me!

**Comment by ineiti** [comment]
OK, fixed. I do like the long format, especially when it comes down to hunt bugs that are happening at a very short time-scale. One thing I can remove is the `+0100 CET`. Is that OK?

**Comment by nikkolasg** [comment]
Ok at least that then.
One last thing, could you add that flag to our binaries ? Like simul/cothority/cothority.go + simul/simul.go?
Or is it not necessary now ? If you coded it, I guess it's not far from using it ;)

**Comment by ineiti** [comment]
Added flags to debug: `-debug` for the level, `-debug-time` for showing time and `-debug-color` for the color. There are also three environment-variables that can be set:

`DEBUG_LVL` - to change the default debug-lvl
`DEBUG_COLOR` - for color
`DEBUG_TIME` - for showing time

**Comment by nikkolasg** [comment]
Fine for me.

**Comment by Liamsi** [comment]
The code looks fine.

**Pull request merged**
