### PR TITLE
Uses the onet client instead of pure websocket

### PR DESCRIPTION
**Pull request by nkcr**
**What this PR does**

This PR removes the "pure" websocket use in Bypros and relies on the Onet client.
@ineiti discussion is open.

### CODE REVIEW

**Comment by nkcr** [comment]
@ineiti this is in response to the commitment we made for the Byzcoin proxy PR to be accepted. This PR makes Bypros rely on Onet, but there are two missing features from Onet that would need to be implemented: `Ping`, and `ReadMessageKeep`. 
As those two features don't seem that big to implement, I can invest some time to implement them, provided we are on the same page and it doesn't end up with an eternal philosophical debate 🙃. So, what's your opinion ?

**Comment by ineiti** [comment]
But I like philosophical discussions, more specifically after some beers...

If you have time, that would be great. If you give a signature and a 'contract' for the `ReadMessageKeep`, we can get philosophical on those.

For the `Ping`, would it be enough to fetch the `/ok` path from the websocket? Or is the ping related to an open websocket?

**Comment by nkcr** [comment]
> If you have time, that would be great. If you give a signature and a 'contract' for the ReadMessageKeep, we can get philosophical on those.

Would have the same signature as `ReadMessage`

> For the Ping, would it be enough to fetch the /ok path from the websocket? Or is the ping related to an open websocket?

I was thinking of the "native" Ping control message (https://tools.ietf.org/html/rfc6455#section-5.5.2), on an open ws connection.

**Comment by ineiti** [comment]
> Would have the same signature as `ReadMessage`

So why not add an `if c.IsKeep` or something to `ReadMessage`?

> I was thinking of the "native" Ping control message (https://tools.ietf.org/html/rfc6455#section-5.5.2), on an open ws connection.

OK, makes sense.

**Comment by nkcr** [comment]
> So why not add an if c.IsKeep or something to ReadMessage?

Could be a possibility. Personally I dislike having this king a attribute that shadows the behavior of a function. That makes thing unclear and prone to error.

**Comment by ineiti** [comment]
> Personally I dislike having this king a attribute that shadows the behavior of a function.

That's why you can have a clean slate with `Dela`... Here I propose to use the flag, as it's already there. Else it's confusing that there is a flag _and_ two different methods, when one would be enough.

**Comment by nkcr** [comment]
> Here I propose to use the flag, as it's already there.

This flag is used for another purpose, and is private. So you want to have an `c.keep` and `c.IsKeep` ?
I'm still not convinced of your solution. Plus my solution allows to add additional parameters if needed.

**Comment by ineiti** [comment]
I don't understand: you say that `ReadMessageKeep` has the same signature as `ReadMessage`, but from the name of the method I suppose it's used for connections that have the `keep` flag.

Even though I just see now that `ReadMessage` is defined on the structure `StreamingConn`. So now I need to understand how that is even different from `ReadMessageKeep`...

**Comment by nkcr** [comment]
We are doing that in the wrong order: please review first https://github.com/dedis/onet/pull/677 then we can come back to this one.

**Review by ineiti — APPROVED** [review]
Looks much nicer to me. I didn't check that the functionality is still the same, so I rely on the tests...

**Pull request merged**
