### PR TITLE
Nsdi base

### PR DESCRIPTION
**Pull request by ineiti**
For NSDI

### CODE REVIEW

**Comment by nikkolasg** [comment]
Mhhhhh I'm unsure of what to do with this branch ? Should we merge it into master ? (let's have a discussion !)

**Comment by Liamsi** [comment]
> Mhhhhh I'm unsure of what to do with this branch ? Should we merge it into master ? (let's have a discussion !)

Copied from @ineiti's mail:

"- merge all NSDI-branches and make a NSDI_2017-branch that we can refer to for later reproduction of the experiments
- make PRs from the NSD_2017-branch back to master for things that are worth it"

**Comment by nikirill** [comment]
Can we maybe merge all these swupdate_1, swupdate_2, ..., nsdi_base into one and call it chainiac?

**Comment by nikkolasg** [comment]
Sounds fine. The thing that are worth it are probably in `services/skipchain` and `sda/` and `network/`

**Comment by nikkolasg** [comment]
> Can we maybe merge all these swupdate_1, swupdate_2, ..., nsdi_base into one and call it chainiac?

I think most of the code is in plotting_595 and swupdate_3. The others branch don't contains anything related to the current code anymore (it went fast!)

**Comment by ineiti** [comment]
I did a `git branch --contains swupdate_3` and got `plotting_595`

@nikkolasg - did you add your scripts to the repo?

I also don't know what to do with the data we used to plot. Also put it in the repo and have it twice, once in cothority and once in the epfl-papers-directory?

**Comment by ineiti** [comment]
Besides that, definitively NOT merge this as-is into master.

**Comment by Liamsi** [comment]
> I also don't know what to do with the data we used to plot. Also put it in the repo and have it twice, once in cothority and once in the epfl-papers-directory? 

If you want other people to be able to reproduce the experiments they should be in the github repo. 
In the epfl papers repo there only should be the *.eps files. Also, we should remove all the duplicate plotit.py files (also from the papers repo). No need to put code in the papers repo, I guess.

**Comment by Liamsi** [comment]
> Besides that, definitively NOT merge this as-is into master.

I agree! Unfortunately we need to make a detailed review and sort out the things which could be relevant for master. Then, we can decide if want to keep the nsdi stuff in a seperate branch or make several smaller PRs out of it (and merge them into master after cleaning them up).

**Comment by ineiti** [comment]
About plotting: @Daeinar asked me to put the scripts in the papers-repo, so that they can be changed. I'll clean them up over there, but probably also leave a copy in here.

Off to some PRs against master...

**Comment by ineiti** [comment]
This pull request will not be merged and stays around here simply as a `tag` of what worked for NSDI. Sooner or later one could move the swupdate-code into master.

**Pull request closed without merging**
