### PR TITLE
external/cothority: run tests before publish

### PR DESCRIPTION
**Pull request by tharvik**
Add a `npm test` pass before publishing.

### CODE REVIEW

**Comment by ineiti** [comment]
Why is `npm test` in `publish.sh` and not in `travis.yml`?

**Comment by tharvik** [comment]
It's useful when publishing a new stable release of a js library, to ensure that what is packed is correctly passing tests.

**Comment by ineiti** [comment]
This time it's me that I don't like having the tests in a script called `publish.sh`, because it's not what I'd expect it to do...

Can you please move the tests to the appropriate part of `travis.yml`? Or create a `package.json` target `publish` that runs the tests and then runs `publish.sh`.

**Comment by tharvik** [comment]
You're right, that makes more sense; updated.

**Pull request merged**
