### PR TITLE
Fix BCAdmin to work for non-admins

### PR DESCRIPTION
**Pull request by ineiti**
The previous version of bcadmin supposed that only the genesis-admin(s)
work on darcs. This PR makes it possible for non-genesis-admins
to create new darcs and to mint their money!

### CODE REVIEW

**Comment by ineiti** [comment]
This is WIP, as the created `bc-xxx.cfg` file is not complete!

**Comment by jeffallen** [comment]
Oops, I just reviewed this and was ready to check it in. I've put it back to WIP.

**Comment by ineiti** [comment]
I'm currently looking at what to do with the `wallet`, `phadmin`, and an eventual new `credadmin` tool. Not sure yet if I will do one or two PRs.

**Comment by ineiti** [comment]
OK, will do (at least) two PRs. Here is a first one to allow `bcadmin` work for a non-genesis-admin. Updated the `README.md` with an example.

**Pull request merged**
