### PR TITLE
Fix LookupSciper problem

### PR DESCRIPTION
**Pull request by jeffallen**
The people.epfl.ch website we are using changed their output format
so adjust to compensate.

### CODE REVIEW

**Comment by jeffallen** [comment]
Please don't commit yet, I realised on the drive home that I meant to make the unit test not depend on external servers, which is a very bad thing to do.

**Comment by jeffallen** [comment]
VPSI says that lookup by SCIPER over HTTPS is going away, and that I need to change this to use LDAP. Will do.

**Comment by jeffallen** [comment]
The build that Github says failed succeeded in Travis, so I don't know what's going on.

**Comment by ineiti** [comment]
> The build that Github says failed succeeded in Travis, so I don't know what's going on.

Did you restart one of the build jobs? Because the `Deploy` only runs if all the other jobs succeed. So if one fails temporarily, and you restart it, you also need to restart `Deploy`. At least I had that problem some time ago...

**Pull request merged**
