### PR TITLE
Remove xerrors dependencies

### PR DESCRIPTION
**Pull request by ineiti**
- replaced all xerrors.Errorf with fmt.Errorf
- replaced all xerrors.New with errors.New
- removed most of cothority/error.go
- replaced all %+v in fmt.Errorf with %v
- replaced most %w in fmt.Errorf with %v, only kept constant errors

Most of `cothority/error.go` seems to be redundant to what the `errors` package offers. 
- [ ] @Gilthoniel confirms the above sentence ;)

### CODE REVIEW

**Comment by tharvik** [comment]
Following issue https://github.com/dedis/cothority/issues/2259

**Comment by Gilthoniel** [comment]
```
 These functions were incorporated into the standard library's errors package in Go 1.13: - Is - As - Unwrap

Also, Errorf's %w verb was incorporated into fmt.Errorf.

Use this package to get equivalent behavior in all supported Go versions.

No other features of this package were included in Go 1.13, and at present there are no plans to include any of them.
```
From the godoc of the xerrors package.

Yes the functions are supported in Go 1.13 but not all the features. We tried to drop xerrors with Dela but the fact is that you loose the benefit of it when it comes to have nice error stacks.

**Comment by ineiti** [comment]
> Yes the functions are supported in Go 1.13 but not all the features. We tried to drop xerrors with Dela but the fact is that you loose the benefit of it when it comes to have nice error stacks.

Oh dang - so I have to do the inverse in fact: replace all `errors.New` with `xerrors.New` and `fmt.Errorf` with `xerrors.Errorf`

**Comment by ineiti** [comment]
This is getting old - closing

**Pull request closed without merging**
