### PR TITLE
added missing methods

### PR DESCRIPTION
**Pull request by ineiti**
Added methods for
- `(Host|SimulationConfig).GetService` - to retrieve the service of a host
- `Client.(Rx|Tx)` - retrieve the bandwidth-data

### CODE REVIEW

**Comment by nikkolasg** [comment]
Can you add also the `Client.Tx()/Rx()` methods please ? I believe it's merged into nsdi_base also

**Comment by ineiti** [comment]
New feature - cool. In fact my comment was wrong. It _is_ `Client.(Rx|Tx)`...

Do you need to remove the `changes request` now?

**Comment by nikkolasg** [comment]
Ahh our friend Travis is not happy !

**Comment by ineiti** [comment]
I thought we removed Travis - no?

**Pull request merged**
