### PR TITLE
PriFi branch merged with cothority master

### PR DESCRIPTION
**Pull request by mahdiz**

### CODE REVIEW

**Comment by nikkolasg** [comment]
Mhhh... what's that ? :) 
The PR is so big, github is very slow to show it...

**Comment by mahdiz** [comment]
The prifi branch (created by @lbarman) needs to be updated with the recent master changes. The former is being used in our prifi repo and was causing problems there due to being outdated. The PR is just targeting the prifi branch of cothority :) 

@lbarman could you please check and merge the PR?

**Comment by lbarman** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Mahdi,
I cannot check the code right now, but I can blindly merge ;) should I do that?
Ludovic

Le 31 octobre 2016 14:38:25 GMT+01:00, Mahdi Zamani <notifications@github.com> a écrit :
>The prifi branch (created by @lbarman) needs to be updated with the
>recent master changes. The former is being used in our prifi repo and
>was causing problems there due to being outdated. The PR is just
>targeting the prifi branch of cothority :)
>
>@lbarman could you please check and merge the PR?
>
>--
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dedis/cothority/pull/661#issuecomment-257295416

- --
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-----BEGIN PGP SIGNATURE-----

iQHGBAEBCgAwKRxMdWRvdmljIEJhcm1hbiAgPGx1ZG92aWMuYmFybWFuQGVwZmwu
Y2g+BQJYF0noAAoJEBjr9SsZWjEDfu0L/323HrI9Md4lz2mDB8jeWO9X1ODsSah0
kQsfh1IvR3faRzTknTmeavuNQFtuYNaOdRoBEMnjPIJNwRkQxG7Ic21otkO99Ald
4KFKJqxnQUeInDHtpAsYdCTXiPHgB2LGuIAaFkSciJd/hg1OvQCZoLF7cJQJiKtx
9B515rcXsvuBcPOaqmI7SyDK3363UJSzBfcER7wymTpenjT/3cjBqQb7f7v0t+vi
LVU1hDz7twlX5gvodeuhI3nwZqTFfsVWEPvl262fnSxgRfnj5r2MMas7g4oLJYpF
HckxnGE+OOMnvVIcrXH4UFONyiFlk75M+DnGsikw45ziZa/NDPEOkWvxV3584OJM
40R93PVD/7njMJBNNOiyJjdsNTsoWXmDOPJD7FQlwW+k1Rn7qSWsNIwZ2DS6W5wg
HLGyesDZpMUGvTGP4Q0s2V68X49ySSQZKgWT2Be3ZKBeOOSiR8Br8nBluNMFyTem
vF8Ymrpe5D+67uPjO+t8pskibA9VfMiEKw==
=bsvu
-----END PGP SIGNATURE-----

**Comment by ineiti** [comment]
I added @mahdiz to the users-list for the cothority-branch, so he can update his own branch as he likes. As this is not against master, there is no problem to do so. If the prifi-guys are OK to have all that out in the open ;)

**Comment by mahdiz** [comment]
@ineiti thanks :)
@lbarman I'll go ahead and merge it with the prifi branch. I've already tested it with our latest PriFi-SDA branch in the prifi_dev repo and works fine. Thanks!

**Pull request merged**
