### PR TITLE
Finding the reason for failing tests on travis 

### LINKED ISSUE #118: Travis fails with test
In `lib/conode` Travis doesn't build the test `TestStamp` for an unknown reason.

### PR DESCRIPTION
**Pull request by Liamsi**
should fix #118 (creating PR from the beginning to see how travis handles this)

### CODE REVIEW

**Comment by ineiti** [comment]
Just delete the `init`-method in `debug_level.go`, as it's not needed anymore.

**Comment by Liamsi** [comment]
Done so, but now travis mysteriously fails again. Will have a look on that soon, moved it back to WIP.

**Comment by Liamsi** [comment]
After renaming the organisation from DeDiS to dedis travis fails again (this is intended). I'll remove further lines from our travis file to see if everything works without the hacks needed for the mixed case organisation name.

**Comment by Liamsi** [comment]
I've done one last simplification. Most of the previous code is obsolete now that the organisation name is all lowercase letters. Please merge if you want  non-failing travis tests

**Comment by nikkolasg** [comment]
Good for me

**Pull request merged**
