### PR TITLE
Trying out stuff for the jvss race / deadlock condition...

### PR DESCRIPTION
**Pull request by nikkolasg**

### CODE REVIEW

**Comment by Liamsi** [comment]
As far as I can tell from travis' output: Looks like you are not running into a race condition bur outputting too much (> 4 Mb). If you make the test less verbose and it succeeds, we are fine :-)

**Comment by Liamsi** [comment]
To me it already looks like you nailed it! (at least before your changes the race-condition occurred during the first or second iteration)

**Comment by nikkolasg** [comment]
I don't get it,  from the output, it still seems to block no ?

**Comment by Liamsi** [comment]
> I don't get it, from the output, it still seems to block no ?

From what I saw yesterday, travis just stops after 4Mb. Did I miss some output stating that it was blocking?

**Pull request merged**
