### PR TITLE
Improve the speed of the integration tests

### PR DESCRIPTION
**Pull request by Gilthoniel**
This replaces the 10 seconds sleep by a ping check to verify when all the conodes have started.

### CODE REVIEW

**Comment by Gilthoniel** [comment]
It would be nice if someone can confirm this works on MacOS aswell.

**Comment by kc1212** [comment]
`authprox/apadmin/test.sh:BCSetup` is failing for me with the message "instruction verification failed: schnorr: invalid signature", does that happen to you too?

**Comment by Gilthoniel** [comment]
Hm no, it's working both locally and on Jenkins for me. Could it be you have out-of-date dependencies ? Like if you have a build folder it won't compile so you end up with a wrong hash for the instructions (or similar)

**Comment by kc1212** [comment]
You're right, deleting the build folder fixed it.

**Pull request merged**
