### PR TITLE
Log print correct

### PR DESCRIPTION
**Pull request by ineiti**
Print correct output for `Print` and others when in debug-output.

### CODE REVIEW

**Comment by nikkolasg** [comment]
OK for me.

**Comment by Liamsi** [comment]
The changes done here: white output if we are in the info level and  ... ? Is there an issue related to this PR describing what this is about?

**Comment by ineiti** [comment]
Sorry - the problem was that `log.Print` didn't give correct line-informations when in debug-mode. It was off by one line in the callstack... Furthermore `log.Info` didn't get correctly tagged when using debug-mode. This patch fixes both.

**Comment by Liamsi** [comment]
OK for me, too!

**Pull request merged**
