### PR TITLE
 Java: use the JSR 356 spec implemented by Tomcat/Apache

### LINKED ISSUE #1825: Java-websockets not closed?
ByzGen said that the java-websockets are not closed when there is an error - is it true?

### PR DESCRIPTION
**Pull request by Gilthoniel**
This changes the implementation of the websocket requests and close the connection when required.

Fixes #1825

### CODE REVIEW

**Comment by Gilthoniel** [comment]
@kc1212 Can you confirm the `StreamHandler` interface can be moved or if it absolutely needs to stay for backwards compatibility ?

**Comment by kc1212** [comment]
It can be moved

**Comment by jeffallen** [comment]
To best check that this works with Android, I want to also add respect for the Url in a Roster, which the Java client does not have yet, so I will add that into this PR, if it's OK with you.

**Comment by Gilthoniel** [comment]
Sure, go for it.

**Comment by Gilthoniel** [comment]
Keeping that around if one day someone needs it

**Pull request closed without merging**
