### PR TITLE
Add GetAllSkipChainIDs to external libraries

### PR DESCRIPTION
**Pull request by louismerlin**
The GetAllSkipChainIDs skipchain message and it's reply were missing from the external libraries.

### CODE REVIEW

**Comment by louismerlin** [comment]
The error is linked to the `SkipBlock` message, which is right next to the message I added, but I don't know why there would be an error.

**Comment by ineiti** [comment]
Thanks - that's because `skipchain.proto` is handwritten, as the `proto.awk` cannot create a correct protofile with embedded structures in `SkipBlock`.

**Comment by louismerlin** [comment]
I also added the prototype for GetSingleBlockByIndex.

**Comment by louismerlin** [comment]
Thanks a lot ! Is it possible to get a new npm package version with the latest changes ? :simple_smile:

**Comment by kc1212** [comment]
Not this week unfortunately, please ask @jeffallen next week to make a npm release.

**Comment by louismerlin** [comment]
Allright no problem, I'll use my fork [@louismerlin/corhority](https://www.npmjs.com/package/@louismerlin/cothority) until then !

**Comment by kc1212** [comment]
@louismerlin we created a new release, version 1.1.19

**Comment by louismerlin** [comment]
Thanks a lot, I'll check it out :grin:

**Pull request merged**
